# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 立泉落落
email: safari@mudan.me
description: "昆虫，野生散养攻城狮，“十分”“业余”摄影Fans。"
url: "https://mudan.me" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  apqx

exclude: [.idea/, npm/node_modules/, npm/src/,
npm/package-lock.json, npm/package.json, npm/README.md, npm/webpack.config.js,
npm/babel.config.json, docs/, README.md, README_CN.md]

# _post 目录下 markdown 转换后的 url 结构
permalink: /post/:categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown

# 设置 highlighter 为 none 才会从 ``` 中生成标准的代码高亮 html，能被 highlight.js 解析
# 但是 GitHub Pages 只支持 Rouge 或 Pygments 的高亮格式，所以不能设置为 none，默认是 Rouge
# highlighter: none
kramdown:
  # 关闭智能引号转换 
  smart_quotes: ["apos", "apos", "quot", "quot"]
  # 虽然不能设置 highlighter: none，但可以禁用 rouge 的输出功能，使 kramdown 输出标准的代码高亮 html，方便 highlight.js 解析
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate-v2

# 为 随笔、转载、诗文、看剧 四个分类生成 RSS Feed
feed:
  disable_in_development: true
  posts_limit: 20
  path: /feed/not-this.xml
  categories:
    - original
    - repost
    - poetry
    - opera

pagination:
  enabled: true
  # 处理的文章目录为 _posts
  collection: "posts"
  # 每页显示 10 篇文章，TagDialog 的初始分页高度动画会随这个参数的增大而变得突兀，因为同样的时间内需要加载更多文章
  per_page: 10
  permalink: ""
  extension: json
  indexpage: "page-:num"
  sort_reverse: true

autopages:
  enabled: true
  collections:
    enabled: false
  categories:
    enabled: true
    layouts:
      - paginate-posts-json.html
    permalink: "/api/paginate/categories/:cat"
    slugify:
      mode: "default"
      case: false
  tags:
    enabled: true
    layouts:
      - paginate-posts-json.html
    permalink: "/api/paginate/tags/:tag"
    slugify:
      mode: "default"
      case: false

# 允许内网设备通过 ip 访问，设置为 localhost 无效🙄
host: 0.0.0.0
